universe        = docker
docker_image    = recad/condornetworktool:latest
executable      = /usr/bin/condornet.sh
arguments       = -f -h 157.253.205.92
should_transfer_files   = YES
transfer_input_files    = Run.sh,condornet.sh
when_to_transfer_output = ON_EXIT
output                  = out.fitting.$(Process).txt
error                   = err.fitting.$(Process).txt
log                     = log.fitting.$(Process).txt
queue 1


